/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BitacoraRouteImport } from './routes/bitacora'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CocinaRouteImport } from './routes/cocina'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TiemposRouteImport } from './routes/tiempos'
import { Route as AccesoSlugRouteImport } from './routes/acceso.$slug'
import { Route as AdminAccesosRouteImport } from './routes/admin.accesos'
import { Route as AdminAjustesRouteImport } from './routes/admin.ajustes'
import { Route as AdminCajasRouteImport } from './routes/admin.cajas'
import { Route as AdminCategoriasInventarioRouteImport } from './routes/admin.categorias-inventario'
import { Route as AdminConteoRouteImport } from './routes/admin.conteo'
import { Route as AdminCuentasCobrarRouteImport } from './routes/admin.cuentas-cobrar'
import { Route as AdminCuentasPagarRouteImport } from './routes/admin.cuentas-pagar'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminFacturasRouteImport } from './routes/admin.facturas'
import { Route as AdminFinanzasRouteImport } from './routes/admin.finanzas'
import { Route as AdminFlujoCajaRouteImport } from './routes/admin.flujo-caja'
import { Route as AdminGastosRouteImport } from './routes/admin.gastos'
import { Route as AdminHorariosRouteImport } from './routes/admin.horarios'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as AdminMixVentasRouteImport } from './routes/admin.mix-ventas'
import { Route as AdminMovimientosRouteImport } from './routes/admin.movimientos'
import { Route as AdminOrdenesCompraRouteImport } from './routes/admin.ordenes-compra'
import { Route as AdminPerdidasGananciasRouteImport } from './routes/admin.perdidas-ganancias'
import { Route as AdminPersonalRouteImport } from './routes/admin.personal'
import { Route as AdminProduccionRouteImport } from './routes/admin.produccion'
import { Route as AdminProveedoresRouteImport } from './routes/admin.proveedores'
import { Route as AdminRecetasFinalesRouteImport } from './routes/admin.recetas-finales'
import { Route as AdminRegistroComprasRouteImport } from './routes/admin.registro-compras'
import { Route as AdminReporteCajasRouteImport } from './routes/admin.reporte-cajas'
import { Route as AdminReportesInventarioRouteImport } from './routes/admin.reportes-inventario'
import { Route as AdminReportesVentasRouteImport } from './routes/admin.reportes-ventas'
import { Route as AdminRespaldoRouteImport } from './routes/admin.respaldo'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminVentasSemanalesRouteImport } from './routes/admin.ventas-semanales'
import { Route as AdminPlataformaIndexRouteImport } from './routes/admin.plataforma.index'
import { Route as AdminPlataformaEmpresaIdRouteImport } from './routes/admin.plataforma.$empresaId'
import { Route as AdminPlataformaBitacoraRouteImport } from './routes/admin.plataforma.bitacora'
import { Route as ApiPublicCajaAutorizarRouteImport } from './routes/api/public/caja/autorizar'
import { Route as ApiPublicCajaCatalogoRouteImport } from './routes/api/public/caja/catalogo'
import { Route as ApiPublicCajaClaveAdminRouteImport } from './routes/api/public/caja/clave-admin'
import { Route as ApiPublicCajaClientesRouteImport } from './routes/api/public/caja/clientes'
import { Route as ApiPublicCajaSincronizarRouteImport } from './routes/api/public/caja/sincronizar'
import { Route as ApiPublicComprobanteClaveAccesoRouteImport } from './routes/api/public/comprobante/$claveAcceso'
import { Route as ApiPublicCronPrecalculoReportesRouteImport } from './routes/api/public/cron/precalculo-reportes'
import { Route as ApiPublicSriContribuyenteRouteImport } from './routes/api/public/sri/contribuyente'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRoute = BitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CocinaRoute = CocinaRouteImport.update({
  id: '/cocina',
  path: '/cocina',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TiemposRoute = TiemposRouteImport.update({
  id: '/tiempos',
  path: '/tiempos',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoSlugRoute = AccesoSlugRouteImport.update({
  id: '/acceso/$slug',
  path: '/acceso/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccesosRoute = AdminAccesosRouteImport.update({
  id: '/accesos',
  path: '/accesos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAjustesRoute = AdminAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCajasRoute = AdminCajasRouteImport.update({
  id: '/cajas',
  path: '/cajas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasInventarioRoute =
  AdminCategoriasInventarioRouteImport.update({
    id: '/categorias-inventario',
    path: '/categorias-inventario',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConteoRoute = AdminConteoRouteImport.update({
  id: '/conteo',
  path: '/conteo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuentasCobrarRoute = AdminCuentasCobrarRouteImport.update({
  id: '/cuentas-cobrar',
  path: '/cuentas-cobrar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuentasPagarRoute = AdminCuentasPagarRouteImport.update({
  id: '/cuentas-pagar',
  path: '/cuentas-pagar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturasRoute = AdminFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanzasRoute = AdminFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlujoCajaRoute = AdminFlujoCajaRouteImport.update({
  id: '/flujo-caja',
  path: '/flujo-caja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGastosRoute = AdminGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHorariosRoute = AdminHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMixVentasRoute = AdminMixVentasRouteImport.update({
  id: '/mix-ventas',
  path: '/mix-ventas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMovimientosRoute = AdminMovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdenesCompraRoute = AdminOrdenesCompraRouteImport.update({
  id: '/ordenes-compra',
  path: '/ordenes-compra',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerdidasGananciasRoute = AdminPerdidasGananciasRouteImport.update({
  id: '/perdidas-ganancias',
  path: '/perdidas-ganancias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonalRoute = AdminPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduccionRoute = AdminProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProveedoresRoute = AdminProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecetasFinalesRoute = AdminRecetasFinalesRouteImport.update({
  id: '/recetas-finales',
  path: '/recetas-finales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistroComprasRoute = AdminRegistroComprasRouteImport.update({
  id: '/registro-compras',
  path: '/registro-compras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReporteCajasRoute = AdminReporteCajasRouteImport.update({
  id: '/reporte-cajas',
  path: '/reporte-cajas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesInventarioRoute = AdminReportesInventarioRouteImport.update({
  id: '/reportes-inventario',
  path: '/reportes-inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesVentasRoute = AdminReportesVentasRouteImport.update({
  id: '/reportes-ventas',
  path: '/reportes-ventas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRespaldoRoute = AdminRespaldoRouteImport.update({
  id: '/respaldo',
  path: '/respaldo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVentasSemanalesRoute = AdminVentasSemanalesRouteImport.update({
  id: '/ventas-semanales',
  path: '/ventas-semanales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlataformaIndexRoute = AdminPlataformaIndexRouteImport.update({
  id: '/plataforma/',
  path: '/plataforma/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlataformaEmpresaIdRoute =
  AdminPlataformaEmpresaIdRouteImport.update({
    id: '/plataforma/$empresaId',
    path: '/plataforma/$empresaId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPlataformaBitacoraRoute = AdminPlataformaBitacoraRouteImport.update({
  id: '/plataforma/bitacora',
  path: '/plataforma/bitacora',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCajaAutorizarRoute = ApiPublicCajaAutorizarRouteImport.update({
  id: '/api/public/caja/autorizar',
  path: '/api/public/caja/autorizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCajaCatalogoRoute = ApiPublicCajaCatalogoRouteImport.update({
  id: '/api/public/caja/catalogo',
  path: '/api/public/caja/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCajaClaveAdminRoute = ApiPublicCajaClaveAdminRouteImport.update({
  id: '/api/public/caja/clave-admin',
  path: '/api/public/caja/clave-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCajaClientesRoute = ApiPublicCajaClientesRouteImport.update({
  id: '/api/public/caja/clientes',
  path: '/api/public/caja/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCajaSincronizarRoute =
  ApiPublicCajaSincronizarRouteImport.update({
    id: '/api/public/caja/sincronizar',
    path: '/api/public/caja/sincronizar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicComprobanteClaveAccesoRoute =
  ApiPublicComprobanteClaveAccesoRouteImport.update({
    id: '/api/public/comprobante/$claveAcceso',
    path: '/api/public/comprobante/$claveAcceso',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPrecalculoReportesRoute =
  ApiPublicCronPrecalculoReportesRouteImport.update({
    id: '/api/public/cron/precalculo-reportes',
    path: '/api/public/cron/precalculo-reportes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSriContribuyenteRoute =
  ApiPublicSriContribuyenteRouteImport.update({
    id: '/api/public/sri/contribuyente',
    path: '/api/public/sri/contribuyente',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bitacora': typeof BitacoraRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/cocina': typeof CocinaRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/menu': typeof MenuRoute
  '/mesas': typeof MesasRoute
  '/reportes': typeof ReportesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tiempos': typeof TiemposRoute
  '/acceso/$slug': typeof AccesoSlugRoute
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/cajas': typeof AdminCajasRoute
  '/admin/categorias-inventario': typeof AdminCategoriasInventarioRoute
  '/admin/conteo': typeof AdminConteoRoute
  '/admin/cuentas-cobrar': typeof AdminCuentasCobrarRoute
  '/admin/cuentas-pagar': typeof AdminCuentasPagarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/flujo-caja': typeof AdminFlujoCajaRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/mix-ventas': typeof AdminMixVentasRoute
  '/admin/movimientos': typeof AdminMovimientosRoute
  '/admin/ordenes-compra': typeof AdminOrdenesCompraRoute
  '/admin/perdidas-ganancias': typeof AdminPerdidasGananciasRoute
  '/admin/personal': typeof AdminPersonalRoute
  '/admin/produccion': typeof AdminProduccionRoute
  '/admin/proveedores': typeof AdminProveedoresRoute
  '/admin/recetas-finales': typeof AdminRecetasFinalesRoute
  '/admin/registro-compras': typeof AdminRegistroComprasRoute
  '/admin/reporte-cajas': typeof AdminReporteCajasRoute
  '/admin/reportes-inventario': typeof AdminReportesInventarioRoute
  '/admin/reportes-ventas': typeof AdminReportesVentasRoute
  '/admin/respaldo': typeof AdminRespaldoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/ventas-semanales': typeof AdminVentasSemanalesRoute
  '/admin/plataforma/$empresaId': typeof AdminPlataformaEmpresaIdRoute
  '/admin/plataforma/bitacora': typeof AdminPlataformaBitacoraRoute
  '/admin/plataforma/': typeof AdminPlataformaIndexRoute
  '/api/public/caja/autorizar': typeof ApiPublicCajaAutorizarRoute
  '/api/public/caja/catalogo': typeof ApiPublicCajaCatalogoRoute
  '/api/public/caja/clave-admin': typeof ApiPublicCajaClaveAdminRoute
  '/api/public/caja/clientes': typeof ApiPublicCajaClientesRoute
  '/api/public/caja/sincronizar': typeof ApiPublicCajaSincronizarRoute
  '/api/public/comprobante/$claveAcceso': typeof ApiPublicComprobanteClaveAccesoRoute
  '/api/public/cron/precalculo-reportes': typeof ApiPublicCronPrecalculoReportesRoute
  '/api/public/sri/contribuyente': typeof ApiPublicSriContribuyenteRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bitacora': typeof BitacoraRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/cocina': typeof CocinaRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/menu': typeof MenuRoute
  '/mesas': typeof MesasRoute
  '/reportes': typeof ReportesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tiempos': typeof TiemposRoute
  '/acceso/$slug': typeof AccesoSlugRoute
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/cajas': typeof AdminCajasRoute
  '/admin/categorias-inventario': typeof AdminCategoriasInventarioRoute
  '/admin/conteo': typeof AdminConteoRoute
  '/admin/cuentas-cobrar': typeof AdminCuentasCobrarRoute
  '/admin/cuentas-pagar': typeof AdminCuentasPagarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/flujo-caja': typeof AdminFlujoCajaRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/mix-ventas': typeof AdminMixVentasRoute
  '/admin/movimientos': typeof AdminMovimientosRoute
  '/admin/ordenes-compra': typeof AdminOrdenesCompraRoute
  '/admin/perdidas-ganancias': typeof AdminPerdidasGananciasRoute
  '/admin/personal': typeof AdminPersonalRoute
  '/admin/produccion': typeof AdminProduccionRoute
  '/admin/proveedores': typeof AdminProveedoresRoute
  '/admin/recetas-finales': typeof AdminRecetasFinalesRoute
  '/admin/registro-compras': typeof AdminRegistroComprasRoute
  '/admin/reporte-cajas': typeof AdminReporteCajasRoute
  '/admin/reportes-inventario': typeof AdminReportesInventarioRoute
  '/admin/reportes-ventas': typeof AdminReportesVentasRoute
  '/admin/respaldo': typeof AdminRespaldoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/ventas-semanales': typeof AdminVentasSemanalesRoute
  '/admin/plataforma/$empresaId': typeof AdminPlataformaEmpresaIdRoute
  '/admin/plataforma/bitacora': typeof AdminPlataformaBitacoraRoute
  '/admin/plataforma': typeof AdminPlataformaIndexRoute
  '/api/public/caja/autorizar': typeof ApiPublicCajaAutorizarRoute
  '/api/public/caja/catalogo': typeof ApiPublicCajaCatalogoRoute
  '/api/public/caja/clave-admin': typeof ApiPublicCajaClaveAdminRoute
  '/api/public/caja/clientes': typeof ApiPublicCajaClientesRoute
  '/api/public/caja/sincronizar': typeof ApiPublicCajaSincronizarRoute
  '/api/public/comprobante/$claveAcceso': typeof ApiPublicComprobanteClaveAccesoRoute
  '/api/public/cron/precalculo-reportes': typeof ApiPublicCronPrecalculoReportesRoute
  '/api/public/sri/contribuyente': typeof ApiPublicSriContribuyenteRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bitacora': typeof BitacoraRoute
  '/caja': typeof CajaRoute
  '/clientes': typeof ClientesRoute
  '/cocina': typeof CocinaRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/menu': typeof MenuRoute
  '/mesas': typeof MesasRoute
  '/reportes': typeof ReportesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tiempos': typeof TiemposRoute
  '/acceso/$slug': typeof AccesoSlugRoute
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/cajas': typeof AdminCajasRoute
  '/admin/categorias-inventario': typeof AdminCategoriasInventarioRoute
  '/admin/conteo': typeof AdminConteoRoute
  '/admin/cuentas-cobrar': typeof AdminCuentasCobrarRoute
  '/admin/cuentas-pagar': typeof AdminCuentasPagarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/flujo-caja': typeof AdminFlujoCajaRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/mix-ventas': typeof AdminMixVentasRoute
  '/admin/movimientos': typeof AdminMovimientosRoute
  '/admin/ordenes-compra': typeof AdminOrdenesCompraRoute
  '/admin/perdidas-ganancias': typeof AdminPerdidasGananciasRoute
  '/admin/personal': typeof AdminPersonalRoute
  '/admin/produccion': typeof AdminProduccionRoute
  '/admin/proveedores': typeof AdminProveedoresRoute
  '/admin/recetas-finales': typeof AdminRecetasFinalesRoute
  '/admin/registro-compras': typeof AdminRegistroComprasRoute
  '/admin/reporte-cajas': typeof AdminReporteCajasRoute
  '/admin/reportes-inventario': typeof AdminReportesInventarioRoute
  '/admin/reportes-ventas': typeof AdminReportesVentasRoute
  '/admin/respaldo': typeof AdminRespaldoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/ventas-semanales': typeof AdminVentasSemanalesRoute
  '/admin/plataforma/$empresaId': typeof AdminPlataformaEmpresaIdRoute
  '/admin/plataforma/bitacora': typeof AdminPlataformaBitacoraRoute
  '/admin/plataforma/': typeof AdminPlataformaIndexRoute
  '/api/public/caja/autorizar': typeof ApiPublicCajaAutorizarRoute
  '/api/public/caja/catalogo': typeof ApiPublicCajaCatalogoRoute
  '/api/public/caja/clave-admin': typeof ApiPublicCajaClaveAdminRoute
  '/api/public/caja/clientes': typeof ApiPublicCajaClientesRoute
  '/api/public/caja/sincronizar': typeof ApiPublicCajaSincronizarRoute
  '/api/public/comprobante/$claveAcceso': typeof ApiPublicComprobanteClaveAccesoRoute
  '/api/public/cron/precalculo-reportes': typeof ApiPublicCronPrecalculoReportesRoute
  '/api/public/sri/contribuyente': typeof ApiPublicSriContribuyenteRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bitacora'
    | '/caja'
    | '/clientes'
    | '/cocina'
    | '/compras'
    | '/configuracion'
    | '/menu'
    | '/mesas'
    | '/reportes'
    | '/reset-password'
    | '/tiempos'
    | '/acceso/$slug'
    | '/admin/accesos'
    | '/admin/ajustes'
    | '/admin/cajas'
    | '/admin/categorias-inventario'
    | '/admin/conteo'
    | '/admin/cuentas-cobrar'
    | '/admin/cuentas-pagar'
    | '/admin/dashboard'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/flujo-caja'
    | '/admin/gastos'
    | '/admin/horarios'
    | '/admin/inventario'
    | '/admin/mix-ventas'
    | '/admin/movimientos'
    | '/admin/ordenes-compra'
    | '/admin/perdidas-ganancias'
    | '/admin/personal'
    | '/admin/produccion'
    | '/admin/proveedores'
    | '/admin/recetas-finales'
    | '/admin/registro-compras'
    | '/admin/reporte-cajas'
    | '/admin/reportes-inventario'
    | '/admin/reportes-ventas'
    | '/admin/respaldo'
    | '/admin/usuarios'
    | '/admin/ventas-semanales'
    | '/admin/plataforma/$empresaId'
    | '/admin/plataforma/bitacora'
    | '/admin/plataforma/'
    | '/api/public/caja/autorizar'
    | '/api/public/caja/catalogo'
    | '/api/public/caja/clave-admin'
    | '/api/public/caja/clientes'
    | '/api/public/caja/sincronizar'
    | '/api/public/comprobante/$claveAcceso'
    | '/api/public/cron/precalculo-reportes'
    | '/api/public/sri/contribuyente'
    | '/api/public/telegram/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bitacora'
    | '/caja'
    | '/clientes'
    | '/cocina'
    | '/compras'
    | '/configuracion'
    | '/menu'
    | '/mesas'
    | '/reportes'
    | '/reset-password'
    | '/tiempos'
    | '/acceso/$slug'
    | '/admin/accesos'
    | '/admin/ajustes'
    | '/admin/cajas'
    | '/admin/categorias-inventario'
    | '/admin/conteo'
    | '/admin/cuentas-cobrar'
    | '/admin/cuentas-pagar'
    | '/admin/dashboard'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/flujo-caja'
    | '/admin/gastos'
    | '/admin/horarios'
    | '/admin/inventario'
    | '/admin/mix-ventas'
    | '/admin/movimientos'
    | '/admin/ordenes-compra'
    | '/admin/perdidas-ganancias'
    | '/admin/personal'
    | '/admin/produccion'
    | '/admin/proveedores'
    | '/admin/recetas-finales'
    | '/admin/registro-compras'
    | '/admin/reporte-cajas'
    | '/admin/reportes-inventario'
    | '/admin/reportes-ventas'
    | '/admin/respaldo'
    | '/admin/usuarios'
    | '/admin/ventas-semanales'
    | '/admin/plataforma/$empresaId'
    | '/admin/plataforma/bitacora'
    | '/admin/plataforma'
    | '/api/public/caja/autorizar'
    | '/api/public/caja/catalogo'
    | '/api/public/caja/clave-admin'
    | '/api/public/caja/clientes'
    | '/api/public/caja/sincronizar'
    | '/api/public/comprobante/$claveAcceso'
    | '/api/public/cron/precalculo-reportes'
    | '/api/public/sri/contribuyente'
    | '/api/public/telegram/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bitacora'
    | '/caja'
    | '/clientes'
    | '/cocina'
    | '/compras'
    | '/configuracion'
    | '/menu'
    | '/mesas'
    | '/reportes'
    | '/reset-password'
    | '/tiempos'
    | '/acceso/$slug'
    | '/admin/accesos'
    | '/admin/ajustes'
    | '/admin/cajas'
    | '/admin/categorias-inventario'
    | '/admin/conteo'
    | '/admin/cuentas-cobrar'
    | '/admin/cuentas-pagar'
    | '/admin/dashboard'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/flujo-caja'
    | '/admin/gastos'
    | '/admin/horarios'
    | '/admin/inventario'
    | '/admin/mix-ventas'
    | '/admin/movimientos'
    | '/admin/ordenes-compra'
    | '/admin/perdidas-ganancias'
    | '/admin/personal'
    | '/admin/produccion'
    | '/admin/proveedores'
    | '/admin/recetas-finales'
    | '/admin/registro-compras'
    | '/admin/reporte-cajas'
    | '/admin/reportes-inventario'
    | '/admin/reportes-ventas'
    | '/admin/respaldo'
    | '/admin/usuarios'
    | '/admin/ventas-semanales'
    | '/admin/plataforma/$empresaId'
    | '/admin/plataforma/bitacora'
    | '/admin/plataforma/'
    | '/api/public/caja/autorizar'
    | '/api/public/caja/catalogo'
    | '/api/public/caja/clave-admin'
    | '/api/public/caja/clientes'
    | '/api/public/caja/sincronizar'
    | '/api/public/comprobante/$claveAcceso'
    | '/api/public/cron/precalculo-reportes'
    | '/api/public/sri/contribuyente'
    | '/api/public/telegram/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BitacoraRoute: typeof BitacoraRoute
  CajaRoute: typeof CajaRoute
  ClientesRoute: typeof ClientesRoute
  CocinaRoute: typeof CocinaRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  MenuRoute: typeof MenuRoute
  MesasRoute: typeof MesasRoute
  ReportesRoute: typeof ReportesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TiemposRoute: typeof TiemposRoute
  AccesoSlugRoute: typeof AccesoSlugRoute
  ApiPublicCajaAutorizarRoute: typeof ApiPublicCajaAutorizarRoute
  ApiPublicCajaCatalogoRoute: typeof ApiPublicCajaCatalogoRoute
  ApiPublicCajaClaveAdminRoute: typeof ApiPublicCajaClaveAdminRoute
  ApiPublicCajaClientesRoute: typeof ApiPublicCajaClientesRoute
  ApiPublicCajaSincronizarRoute: typeof ApiPublicCajaSincronizarRoute
  ApiPublicComprobanteClaveAccesoRoute: typeof ApiPublicComprobanteClaveAccesoRoute
  ApiPublicCronPrecalculoReportesRoute: typeof ApiPublicCronPrecalculoReportesRoute
  ApiPublicSriContribuyenteRoute: typeof ApiPublicSriContribuyenteRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora': {
      id: '/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof BitacoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocina': {
      id: '/cocina'
      path: '/cocina'
      fullPath: '/cocina'
      preLoaderRoute: typeof CocinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiempos': {
      id: '/tiempos'
      path: '/tiempos'
      fullPath: '/tiempos'
      preLoaderRoute: typeof TiemposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso/$slug': {
      id: '/acceso/$slug'
      path: '/acceso/$slug'
      fullPath: '/acceso/$slug'
      preLoaderRoute: typeof AccesoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accesos': {
      id: '/admin/accesos'
      path: '/accesos'
      fullPath: '/admin/accesos'
      preLoaderRoute: typeof AdminAccesosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ajustes': {
      id: '/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AdminAjustesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cajas': {
      id: '/admin/cajas'
      path: '/cajas'
      fullPath: '/admin/cajas'
      preLoaderRoute: typeof AdminCajasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias-inventario': {
      id: '/admin/categorias-inventario'
      path: '/categorias-inventario'
      fullPath: '/admin/categorias-inventario'
      preLoaderRoute: typeof AdminCategoriasInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteo': {
      id: '/admin/conteo'
      path: '/conteo'
      fullPath: '/admin/conteo'
      preLoaderRoute: typeof AdminConteoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuentas-cobrar': {
      id: '/admin/cuentas-cobrar'
      path: '/cuentas-cobrar'
      fullPath: '/admin/cuentas-cobrar'
      preLoaderRoute: typeof AdminCuentasCobrarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuentas-pagar': {
      id: '/admin/cuentas-pagar'
      path: '/cuentas-pagar'
      fullPath: '/admin/cuentas-pagar'
      preLoaderRoute: typeof AdminCuentasPagarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturas': {
      id: '/admin/facturas'
      path: '/facturas'
      fullPath: '/admin/facturas'
      preLoaderRoute: typeof AdminFacturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzas': {
      id: '/admin/finanzas'
      path: '/finanzas'
      fullPath: '/admin/finanzas'
      preLoaderRoute: typeof AdminFinanzasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flujo-caja': {
      id: '/admin/flujo-caja'
      path: '/flujo-caja'
      fullPath: '/admin/flujo-caja'
      preLoaderRoute: typeof AdminFlujoCajaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gastos': {
      id: '/admin/gastos'
      path: '/gastos'
      fullPath: '/admin/gastos'
      preLoaderRoute: typeof AdminGastosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/horarios': {
      id: '/admin/horarios'
      path: '/horarios'
      fullPath: '/admin/horarios'
      preLoaderRoute: typeof AdminHorariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mix-ventas': {
      id: '/admin/mix-ventas'
      path: '/mix-ventas'
      fullPath: '/admin/mix-ventas'
      preLoaderRoute: typeof AdminMixVentasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movimientos': {
      id: '/admin/movimientos'
      path: '/movimientos'
      fullPath: '/admin/movimientos'
      preLoaderRoute: typeof AdminMovimientosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ordenes-compra': {
      id: '/admin/ordenes-compra'
      path: '/ordenes-compra'
      fullPath: '/admin/ordenes-compra'
      preLoaderRoute: typeof AdminOrdenesCompraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perdidas-ganancias': {
      id: '/admin/perdidas-ganancias'
      path: '/perdidas-ganancias'
      fullPath: '/admin/perdidas-ganancias'
      preLoaderRoute: typeof AdminPerdidasGananciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/personal': {
      id: '/admin/personal'
      path: '/personal'
      fullPath: '/admin/personal'
      preLoaderRoute: typeof AdminPersonalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produccion': {
      id: '/admin/produccion'
      path: '/produccion'
      fullPath: '/admin/produccion'
      preLoaderRoute: typeof AdminProduccionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proveedores': {
      id: '/admin/proveedores'
      path: '/proveedores'
      fullPath: '/admin/proveedores'
      preLoaderRoute: typeof AdminProveedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recetas-finales': {
      id: '/admin/recetas-finales'
      path: '/recetas-finales'
      fullPath: '/admin/recetas-finales'
      preLoaderRoute: typeof AdminRecetasFinalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registro-compras': {
      id: '/admin/registro-compras'
      path: '/registro-compras'
      fullPath: '/admin/registro-compras'
      preLoaderRoute: typeof AdminRegistroComprasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reporte-cajas': {
      id: '/admin/reporte-cajas'
      path: '/reporte-cajas'
      fullPath: '/admin/reporte-cajas'
      preLoaderRoute: typeof AdminReporteCajasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes-inventario': {
      id: '/admin/reportes-inventario'
      path: '/reportes-inventario'
      fullPath: '/admin/reportes-inventario'
      preLoaderRoute: typeof AdminReportesInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes-ventas': {
      id: '/admin/reportes-ventas'
      path: '/reportes-ventas'
      fullPath: '/admin/reportes-ventas'
      preLoaderRoute: typeof AdminReportesVentasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/respaldo': {
      id: '/admin/respaldo'
      path: '/respaldo'
      fullPath: '/admin/respaldo'
      preLoaderRoute: typeof AdminRespaldoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ventas-semanales': {
      id: '/admin/ventas-semanales'
      path: '/ventas-semanales'
      fullPath: '/admin/ventas-semanales'
      preLoaderRoute: typeof AdminVentasSemanalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plataforma/': {
      id: '/admin/plataforma/'
      path: '/plataforma'
      fullPath: '/admin/plataforma/'
      preLoaderRoute: typeof AdminPlataformaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plataforma/$empresaId': {
      id: '/admin/plataforma/$empresaId'
      path: '/plataforma/$empresaId'
      fullPath: '/admin/plataforma/$empresaId'
      preLoaderRoute: typeof AdminPlataformaEmpresaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plataforma/bitacora': {
      id: '/admin/plataforma/bitacora'
      path: '/plataforma/bitacora'
      fullPath: '/admin/plataforma/bitacora'
      preLoaderRoute: typeof AdminPlataformaBitacoraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/caja/autorizar': {
      id: '/api/public/caja/autorizar'
      path: '/api/public/caja/autorizar'
      fullPath: '/api/public/caja/autorizar'
      preLoaderRoute: typeof ApiPublicCajaAutorizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/caja/catalogo': {
      id: '/api/public/caja/catalogo'
      path: '/api/public/caja/catalogo'
      fullPath: '/api/public/caja/catalogo'
      preLoaderRoute: typeof ApiPublicCajaCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/caja/clave-admin': {
      id: '/api/public/caja/clave-admin'
      path: '/api/public/caja/clave-admin'
      fullPath: '/api/public/caja/clave-admin'
      preLoaderRoute: typeof ApiPublicCajaClaveAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/caja/clientes': {
      id: '/api/public/caja/clientes'
      path: '/api/public/caja/clientes'
      fullPath: '/api/public/caja/clientes'
      preLoaderRoute: typeof ApiPublicCajaClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/caja/sincronizar': {
      id: '/api/public/caja/sincronizar'
      path: '/api/public/caja/sincronizar'
      fullPath: '/api/public/caja/sincronizar'
      preLoaderRoute: typeof ApiPublicCajaSincronizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comprobante/$claveAcceso': {
      id: '/api/public/comprobante/$claveAcceso'
      path: '/api/public/comprobante/$claveAcceso'
      fullPath: '/api/public/comprobante/$claveAcceso'
      preLoaderRoute: typeof ApiPublicComprobanteClaveAccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/precalculo-reportes': {
      id: '/api/public/cron/precalculo-reportes'
      path: '/api/public/cron/precalculo-reportes'
      fullPath: '/api/public/cron/precalculo-reportes'
      preLoaderRoute: typeof ApiPublicCronPrecalculoReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sri/contribuyente': {
      id: '/api/public/sri/contribuyente'
      path: '/api/public/sri/contribuyente'
      fullPath: '/api/public/sri/contribuyente'
      preLoaderRoute: typeof ApiPublicSriContribuyenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccesosRoute: typeof AdminAccesosRoute
  AdminAjustesRoute: typeof AdminAjustesRoute
  AdminCajasRoute: typeof AdminCajasRoute
  AdminCategoriasInventarioRoute: typeof AdminCategoriasInventarioRoute
  AdminConteoRoute: typeof AdminConteoRoute
  AdminCuentasCobrarRoute: typeof AdminCuentasCobrarRoute
  AdminCuentasPagarRoute: typeof AdminCuentasPagarRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFacturasRoute: typeof AdminFacturasRoute
  AdminFinanzasRoute: typeof AdminFinanzasRoute
  AdminFlujoCajaRoute: typeof AdminFlujoCajaRoute
  AdminGastosRoute: typeof AdminGastosRoute
  AdminHorariosRoute: typeof AdminHorariosRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminMixVentasRoute: typeof AdminMixVentasRoute
  AdminMovimientosRoute: typeof AdminMovimientosRoute
  AdminOrdenesCompraRoute: typeof AdminOrdenesCompraRoute
  AdminPerdidasGananciasRoute: typeof AdminPerdidasGananciasRoute
  AdminPersonalRoute: typeof AdminPersonalRoute
  AdminProduccionRoute: typeof AdminProduccionRoute
  AdminProveedoresRoute: typeof AdminProveedoresRoute
  AdminRecetasFinalesRoute: typeof AdminRecetasFinalesRoute
  AdminRegistroComprasRoute: typeof AdminRegistroComprasRoute
  AdminReporteCajasRoute: typeof AdminReporteCajasRoute
  AdminReportesInventarioRoute: typeof AdminReportesInventarioRoute
  AdminReportesVentasRoute: typeof AdminReportesVentasRoute
  AdminRespaldoRoute: typeof AdminRespaldoRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVentasSemanalesRoute: typeof AdminVentasSemanalesRoute
  AdminPlataformaEmpresaIdRoute: typeof AdminPlataformaEmpresaIdRoute
  AdminPlataformaBitacoraRoute: typeof AdminPlataformaBitacoraRoute
  AdminPlataformaIndexRoute: typeof AdminPlataformaIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccesosRoute: AdminAccesosRoute,
  AdminAjustesRoute: AdminAjustesRoute,
  AdminCajasRoute: AdminCajasRoute,
  AdminCategoriasInventarioRoute: AdminCategoriasInventarioRoute,
  AdminConteoRoute: AdminConteoRoute,
  AdminCuentasCobrarRoute: AdminCuentasCobrarRoute,
  AdminCuentasPagarRoute: AdminCuentasPagarRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFacturasRoute: AdminFacturasRoute,
  AdminFinanzasRoute: AdminFinanzasRoute,
  AdminFlujoCajaRoute: AdminFlujoCajaRoute,
  AdminGastosRoute: AdminGastosRoute,
  AdminHorariosRoute: AdminHorariosRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminMixVentasRoute: AdminMixVentasRoute,
  AdminMovimientosRoute: AdminMovimientosRoute,
  AdminOrdenesCompraRoute: AdminOrdenesCompraRoute,
  AdminPerdidasGananciasRoute: AdminPerdidasGananciasRoute,
  AdminPersonalRoute: AdminPersonalRoute,
  AdminProduccionRoute: AdminProduccionRoute,
  AdminProveedoresRoute: AdminProveedoresRoute,
  AdminRecetasFinalesRoute: AdminRecetasFinalesRoute,
  AdminRegistroComprasRoute: AdminRegistroComprasRoute,
  AdminReporteCajasRoute: AdminReporteCajasRoute,
  AdminReportesInventarioRoute: AdminReportesInventarioRoute,
  AdminReportesVentasRoute: AdminReportesVentasRoute,
  AdminRespaldoRoute: AdminRespaldoRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVentasSemanalesRoute: AdminVentasSemanalesRoute,
  AdminPlataformaEmpresaIdRoute: AdminPlataformaEmpresaIdRoute,
  AdminPlataformaBitacoraRoute: AdminPlataformaBitacoraRoute,
  AdminPlataformaIndexRoute: AdminPlataformaIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BitacoraRoute: BitacoraRoute,
  CajaRoute: CajaRoute,
  ClientesRoute: ClientesRoute,
  CocinaRoute: CocinaRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  MenuRoute: MenuRoute,
  MesasRoute: MesasRoute,
  ReportesRoute: ReportesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TiemposRoute: TiemposRoute,
  AccesoSlugRoute: AccesoSlugRoute,
  ApiPublicCajaAutorizarRoute: ApiPublicCajaAutorizarRoute,
  ApiPublicCajaCatalogoRoute: ApiPublicCajaCatalogoRoute,
  ApiPublicCajaClaveAdminRoute: ApiPublicCajaClaveAdminRoute,
  ApiPublicCajaClientesRoute: ApiPublicCajaClientesRoute,
  ApiPublicCajaSincronizarRoute: ApiPublicCajaSincronizarRoute,
  ApiPublicComprobanteClaveAccesoRoute: ApiPublicComprobanteClaveAccesoRoute,
  ApiPublicCronPrecalculoReportesRoute: ApiPublicCronPrecalculoReportesRoute,
  ApiPublicSriContribuyenteRoute: ApiPublicSriContribuyenteRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
