CREATE TYPE public.order_status AS ENUM ('abierto','en_cocina','listo','pagado','cancelado');
CREATE TYPE public.item_status AS ENUM ('pendiente','preparando','listo','entregado');

CREATE TABLE public.categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.categories TO authenticated;
GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "categories_all_auth" ON public.categories FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id uuid REFERENCES public.categories(id) ON DELETE SET NULL,
  name text NOT NULL,
  description text,
  price numeric(10,2) NOT NULL DEFAULT 0,
  available boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT ALL ON public.products TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "products_all_auth" ON public.products FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.restaurant_tables (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  seats int NOT NULL DEFAULT 4,
  zone text NOT NULL DEFAULT 'Salón',
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.restaurant_tables TO authenticated;
GRANT ALL ON public.restaurant_tables TO service_role;
ALTER TABLE public.restaurant_tables ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tables_all_auth" ON public.restaurant_tables FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  folio bigint GENERATED BY DEFAULT AS IDENTITY,
  table_id uuid REFERENCES public.restaurant_tables(id) ON DELETE SET NULL,
  service_type text NOT NULL DEFAULT 'mesa',
  customer_name text,
  status public.order_status NOT NULL DEFAULT 'abierto',
  subtotal numeric(10,2) NOT NULL DEFAULT 0,
  total numeric(10,2) NOT NULL DEFAULT 0,
  payment_method text,
  notes text,
  created_by uuid,
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders TO authenticated;
GRANT ALL ON public.orders TO service_role;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "orders_all_auth" ON public.orders FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  unit_price numeric(10,2) NOT NULL DEFAULT 0,
  quantity int NOT NULL DEFAULT 1,
  notes text,
  status public.item_status NOT NULL DEFAULT 'pendiente',
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_items TO authenticated;
GRANT ALL ON public.order_items TO service_role;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "order_items_all_auth" ON public.order_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX idx_order_items_order ON public.order_items(order_id);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_created ON public.orders(created_at);

CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ LANGUAGE plpgsql SET search_path = public;
CREATE TRIGGER orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_items;

INSERT INTO public.categories (id, name, sort_order) VALUES
 ('11111111-1111-1111-1111-111111111101','Entradas',1),
 ('11111111-1111-1111-1111-111111111102','Platos fuertes',2),
 ('11111111-1111-1111-1111-111111111103','Tacos',3),
 ('11111111-1111-1111-1111-111111111104','Bebidas',4),
 ('11111111-1111-1111-1111-111111111105','Postres',5);

INSERT INTO public.products (category_id, name, description, price) VALUES
 ('11111111-1111-1111-1111-111111111101','Guacamole con totopos','Aguacate, cilantro, limón',95.00),
 ('11111111-1111-1111-1111-111111111101','Queso fundido','Con chorizo y tortillas',110.00),
 ('11111111-1111-1111-1111-111111111101','Sopa de tortilla','Caldo de jitomate, aguacate',85.00),
 ('11111111-1111-1111-1111-111111111102','Arrachera 300g','Con frijoles charros',285.00),
 ('11111111-1111-1111-1111-111111111102','Enchiladas verdes','Pollo, crema y queso',165.00),
 ('11111111-1111-1111-1111-111111111102','Pescado a la talla','Con arroz y ensalada',245.00),
 ('11111111-1111-1111-1111-111111111102','Chiles en nogada','Temporada',290.00),
 ('11111111-1111-1111-1111-111111111103','Taco de pastor','Orden de 3',75.00),
 ('11111111-1111-1111-1111-111111111103','Taco de suadero','Orden de 3',80.00),
 ('11111111-1111-1111-1111-111111111103','Taco de campechano','Orden de 3',85.00),
 ('11111111-1111-1111-1111-111111111104','Agua de horchata','1 litro',55.00),
 ('11111111-1111-1111-1111-111111111104','Refresco','355 ml',35.00),
 ('11111111-1111-1111-1111-111111111104','Cerveza artesanal','355 ml',75.00),
 ('11111111-1111-1111-1111-111111111104','Café de olla','Taza',45.00),
 ('11111111-1111-1111-1111-111111111105','Flan napolitano','Rebanada',70.00),
 ('11111111-1111-1111-1111-111111111105','Pastel de tres leches','Rebanada',80.00);

INSERT INTO public.restaurant_tables (name, seats, zone, sort_order) VALUES
 ('Mesa 1',2,'Salón',1),('Mesa 2',4,'Salón',2),('Mesa 3',4,'Salón',3),
 ('Mesa 4',6,'Salón',4),('Mesa 5',2,'Barra',5),('Mesa 6',2,'Barra',6),
 ('Mesa 7',8,'Terraza',7),('Mesa 8',4,'Terraza',8);